### ISSUE TITLE
Missing component libraries

### ISSUE THREAD

**Issue by penguin359** [Ttl/fmcw#3]
It appears that a few components have changed since the 2014 release of the libraries and the pins of the new components don't match up. In particular, resistors and capacitors are shorter breaking the wire connections to the pins. The other components that are different are the four connectors used across the two sheets, wlan_radar.sch and mcu.sch. In the case of the connectors, it appears that their names have changed from CONN_2 and CONN_6 to CONN_01X02 and CONN_01X06. Updating the schematic files with the correct names makes the components show up, but their pin positions still don't line up so the wires have to be re-drawn.

I've re-attached all the wires to the appropriate pins to match with the updated components and the ERC now shows only three errors/warnings that appear have been there with the original schematic. However, I'd prefer to just keep the original schematic and it's library of components. Normally, a cached library, wlan_radar-cache.lib in this case, is created to house all the components used in a design. This allows the design to move across systems that might have a different set of libraries installed. Do you have a copy of the original library cache and can you include it in the Git repository so that the design files will still be intact regardless of the set of libraries installed on the local system?

**Comment by Ttl** [comment]
I added the library cache file.
