### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by penguin359** [Ttl/fmcw#4]
Several header files (and most likely there source equivalents) seem to be missing from the firmware folder. Specifically, the following lines cause issues:

#include "USB1.h"
#include "USB0.h"
#include "CDC1.h"
#include "Tx1.h"
#include "Rx1.h"
#include "CS1.h"
#include "WAIT1.h"
#include "UTIL1.h"

The above list can't be found by Kinetis Design Studio or by any manual searching. Did you originally generate the code using the Microcontrollers Driver Suite from Freescale? I have not been able to find where the auto-generated code comes from.

**Comment by Ttl** [comment]
These headers are for mcuoneclipse components. You can download them from: http://sourceforge.net/projects/mcuoneclipse/files/PEx%20Components/
