### ISSUE TITLE
Is design usable for EQ Radio?

### ISSUE THREAD

**Issue by crawfordcomeaux** [Ttl/fmcw#5]
I noticed you blogged about measuring breathing & heart rate. (http://hforsten.com/heartbeat-detection-with-radar.html)

 Do you think this design could be used to implement the system in this paper?
http://eqradio.csail.mit.edu/files/eqradio-paper.pdf

**Comment by Ttl** [comment]
Probably not, due to the low data rate of the radar. Microcontroller isn't fast enough to transmit all of the sweeps continuously so the data would have significant gaps. My other radar design (fmcw2) might work.
